apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apr_spring2
  description: "teste"
  annotations:
    github.com/project-slug: veecode-homolog/apr_spring2
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: "apr_spring2"
    vault.io/secrets-path: "apr_spring2"
    grafana/tag-selector: "apr_spring2"
    grafana/alert-label-selector: "alertname=apr_spring2"
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: "apr_spring2"
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/admin"



